# ═══════════════════════════════════════════════════════════════════════════
# GpuChile Frontend - Kubernetes Service for Kind
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    app: frontend
    component: web
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080  # Accesible desde el host en http://localhost:3000
    protocol: TCP
  sessionAffinity: None
